# Generated by Django 5.1.3 on 2024-11-18 22:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('profiles', '0003_profilefeedimtem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileFeedImtem',
            new_name='ProfileFeedItem',
        ),
    ]
